### ISSUE TITLE
How call this script from Nagios ?

### ISSUE THREAD

**Issue by olivierHa** [lorello/nagios-checks#2]
Hello, 

I got a stupid question : how do you call this script from Nagios ?
Do you got an another script that do a curl and parse the output ?

Regards

Olivier

**Comment by CZAirwolf** [comment]
snmpd.conf + exec + check_snmp_script_result.pl

Anyway, problem with running from CLI, www browser is OK:
/etc/php5/cli/php.ini:
[opcache]
opcache_enable = 1
opcache.memory_consumption=256
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.fast_shutdown=1
opcache.enable_cli=1

root@server:/usr/lib/nagios/plugins# php5 ./check_opcache.php 
CRITICAL - Zend OPcache 7.0.3 memory hitrate is under critical level 0% | size=268435456 enabled=1 cache_full= used_memory=10951808 free_memory=257483648 wasted_memory=0 current_wasted_percentage=0 num_cached_scripts=1 num_cached_keys=2 max_cached_keys=7963 hits=0 oom_restarts=0 hash_restarts=0 manual_restarts=0 misses=1 blacklist_misses=0 blacklist_miss_ratio=0 opcache_hit_rate=0

**Comment by olivierHa** [comment]
I've written a little python script that calls an url, parse the output (expected nrpe syntax) to do the job.

**Comment by CZAirwolf** [comment]
I solved not getting values from cli by using curl via snmpd.conf, output is parsed by check_snmp_script_result.pl:
exec opcache curl -s  http://wwwserver/opcache-status/check_opcache.php

**Comment by lorello** [comment]
We have simple check_http that parses the output, but you can use something like [this](http://exchange.nagios.org/directory/Plugins/Network-Protocols/HTTP/check_http-perl-script/details) or [this](http://linux.101hacks.com/unix/check-http/)

**Comment by francescor** [comment]
following your suggestion (using http://exchange.nagios.org/directory/Plugins/Network-Protocols/HTTP/check_http-perl-script/details )
we had this to work

``` bash
/usr/lib/nagios/plugins/check_http.pl  -H devnginx2.opencontent.it -u /check-opcache.php -C '^(CRITICAL|UNKNOWN)' -W ^WARNING
```

so we've created  /etc/nagios-plugins/config/check_http_opcache.cfg with

```
#check_http_opcache 
define command{
        command_name    check_http_opcache
        command_line    /usr/lib/nagios/plugins/check_http.pl -H '$ARG1$' -u '$ARG2$' -C '$ARG3$' -W '$ARG4$'
        }
```

so to have:

```
define service {
        host_name           myhost.domain.com
        service_description check_opcache
        use                 generic-service
        check_command       check_http_opcache!devnginx2.opencontent.it!/check-opcache.php!^(CRITICAL|UNKNOWN)!^WARNING
}
```

**Comment by francescor** [comment]
btw, it appears check_http.pl is missing correct exit code. I've fixed it by replacing

``` perl
if ($response->is_success) {
  print "Status: OK\n";
}
```

with 

``` perl
if ($response->is_success) {
  print "Status: OK\n";
  exit $ERRORS{"OK"};
}

```
